
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres?sslmode=disable
    volumes:
      - ./backend:/app
    command: ["air"]
    ports:
      - "8080:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: 512M  

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    deploy:
      resources:
        limits:
          memory: 512M

volumes:
  postgres-data:
